### ISSUE TITLE
Directories have an "unknown MIME type"

### ISSUE THREAD

**Issue by timmli** [FrostyX/dired-open-with#7]
Everything works fine except for one thing: when trying to open a directory/folder with `dired-open-with`, only the message `File with unknown MIME type: <foldername>` is displayed. I'm on Linux Mint. The expected behavior would be, in my case, that the system file browser can be selected. 

It would be great if this could be fixed/added.

BTW: Thanks for this great package!

**Comment by FrostyX** [comment]
> BTW: Thanks for this great package!

Thank you for the kind words, much appreciated :-)

> when trying to open a directory/folder with dired-open-with

I didn't realize directories have a MIME type too and that the package could work on them as well. Thats really cool.
Can you please try if PR #8 works for you?

**Comment by timmli** [comment]
Seems to work :+1:
